// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
..........................
..........................
..........................
..........................
..22222...................
..233222..................
..233322..................
..23332...................
..22222...................
......f...66666...........
......f...6f6f6...........
......f...6f6f6...........
......f....666............
......f...e121e...........
......6eeee121ee..........
......f...e121e.e.........
......f...e1f1e.e.........
......f...88888.6.........
..........88.88...........
..........88.88...........
..........88.88...........
..........ff.ff...........
..........................
..........................
..........................
..........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
